version: '3.5'
services:

  fluentbit:
    image: fluent/fluent-bit:1.2
    command: /fluent-bit/bin/fluent-bit -c /var/conf/fluentbit.conf
    # ports: 
    #   - "5170:5170"
    volumes: 
      - ../src/fluentbit/conf:/var/conf
    environment: 
      - ELASTIC_SEARCH_HOST=elasticsearch
      - ELASTIC_SEARCH_PORT=9200
    depends_on: 
      - elasticsearch
    networks:
      - svapy_infrustructure_logging_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    # volumes: 
      # - /mnt/svayp/logging/elasticsearch/data:/usr/share/elasticsearch/
    networks:
      - svapy_infrustructure_logging_network

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0 
    ports:
      - "5000:5601"
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on: 
      - elasticsearch
    networks:
      - svapy_infrustructure_logging_network

networks:
  svapy_infrustructure_logging_network:
    name: svapy_infrustructure_logging_network
    driver: bridge