version: '3.7'
services:
  fluentbit:
    image: fluent/fluent-bit:1.2
    command: /fluent-bit/bin/fluent-bit -c /var/conf/fluentbit.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports: 
      - "5170:5170"
    configs:
      - source: fluentbit_config
        target: /var/conf/fluentbit.conf
      - source: fluentbit_parsers_config
        target: /var/conf/parsers.conf
    environment: 
      - ELASTIC_SEARCH_HOST=elasticsearch
      - ELASTIC_SEARCH_PORT=9200
    depends_on: 
      - elasticsearch
    networks:
      - exlinetr_infrustructure_logging_network

  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
    networks:
      - exlinetr_infrustructure_logging_network

  kibana:
    image: kibana:7.6.2
    ports: 
      - "5601:5601"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.kibana.service=kibana"
        - "traefik.http.routers.kibana.rule=Host(`kibana.exlinetr.com`)"
        - "traefik.http.routers.kibana.entrypoints=web"
        - "traefik.http.services.kibana.loadbalancer.server.port=5601"
        - "traefik.http.services.kibana.loadbalancer.server.scheme=http"
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on: 
      - elasticsearch
    networks:
      - exlinetr_infrustructure_logging_network

networks:
  exlinetr_infrustructure_logging_network:
    name: exlinetr_infrustructure_logging_network

configs:
  fluentbit_config:
    external: true
  fluentbit_parsers_config:
    external: true

volumes:
  exlinetr_elasticsearch_data: