version: '3.7'
services:
  fluentbit:
    image: fluent/fluent-bit:1.2
    command: /fluent-bit/bin/fluent-bit -c /var/conf/fluentbit.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.tcp.routers.fluentbit.service=fluentbit"
        - "traefik.tcp.routers.fluentbit.rule=HostSNI(`fluentbit.exlinetr.com`)"
        # - "traefik.tcp.routers.fluentbit.tls=true"
        - "traefik.tcp.services.fluentbit.loadbalancer.server.port=5170"
        - "traefik.tcp.services.fluentbit.loadbalancer.terminationdelay=100"
    # ports: 
    #   - "5170:5170"
    configs:
      - source: fluentbit_config
        target: /var/conf/fluentbit.conf
      - source: fluentbit_parsers_config
        target: /var/conf/parsers.conf
    environment: 
      - ELASTIC_SEARCH_HOST=elasticsearch
      - ELASTIC_SEARCH_PORT=9200
      - ELASTIC_USERNMAE=furkaandogan
      - ELASTIC_PASSWORD=frkn5268.,
    depends_on: 
      - elasticsearch
    networks:
      - exlinetr_infrustructure_logging_network

  elasticsearch:
    image: elasticsearch:7.6.2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.elasticsearch.service=elasticsearch"
        - "traefik.http.routers.elasticsearch.rule=Host(`elasticsearch.exlinetr.com`)"
        - "traefik.http.routers.elasticsearch.entrypoints=web"
        - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"
        - "traefik.http.services.elasticsearch.loadbalancer.server.scheme=http"
        - "traefik.http.middlewares.elasticsearch-auth.basicauth.users=furkaandogan:{SHA}90St/4Twu+l5Y9zfJQNDprYI+Ek="
        - "traefik.http.routers.elasticsearch.middlewares=elasticsearch-auth"
    environment:
      - discovery.type=single-node
    volumes:
      - /mnt/storage/elasticsearch/data:/usr/share/elasticsearch/data
      - /mnt/storage/elasticsearch/config:/usr/share/elasticsearch/config
    networks:
      - exlinetr_infrustructure_logging_network
      - traefik_network

  kibana:
    image: kibana:7.6.2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.kibana.service=kibana"
        - "traefik.http.routers.kibana.rule=Host(`kibana.exlinetr.com`)"
        - "traefik.http.routers.kibana.entrypoints=web"
        - "traefik.http.services.kibana.loadbalancer.server.port=5601"
        - "traefik.http.services.kibana.loadbalancer.server.scheme=http"
        - "traefik.http.middlewares.kibana-auth.basicauth.users=furkaandogan:{SHA}90St/4Twu+l5Y9zfJQNDprYI+Ek="
        - "traefik.http.routers.kibana.middlewares=kibana-auth"
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on: 
      - elasticsearch
    networks:
      - exlinetr_infrustructure_logging_network
      - traefik_network

networks:
  traefik_network:
    external: true
  exlinetr_infrustructure_logging_network:
    name: exlinetr_infrustructure_logging_network

configs:
  fluentbit_config:
    external: true
  fluentbit_parsers_config:
    external: true

volumes:
  exlinetr_elasticsearch_data: